name: build
on:
  push:
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:  # TODO: Add all the following OSes...
        # os: [macos-13, macos-latest, ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-2025]
        os: [macos-13, ubuntu-latest, ubuntu-24.04-arm]  # macOS on Intel and Ubuntu builds succeed.
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - shell: bash  # Not pwsh on Windows
        run: |
          ./autogen.sh
          ./configure
          make
          sudo make install
